### PR TITLE
Don't minify CSS; fixes everything

### PR DESCRIPTION
**Pull request by ojame**
fixes the spin

### CODE REVIEW

**Comment by grapegravity** [comment]
How did this fix the spin? Seems like a weird thing to have to change to fix that…

**Comment by deoxxa** [comment]
The newer version of css-loader included a change that meant CSS was minified by default. Apparently one of the minimisation steps is to shorten keyframe names. That shortening must be broken somehow, because it resulted in two keyframe set definitions having the same (shortened) name, so the loading keyframe set was being applied to the task's transition.

**Comment by deoxxa** [comment]
Personally, I blame CSS for being a horrible mess of global state by design.

**Comment by ojame** [comment]
Probably due to the way (or order) stylesheets are imported - maybe minimising them before merging, im not sure.

**Comment by grapegravity** [comment]
That’s a really weird one! Thanks for the context :smile:

**Pull request merged**
