### PR TITLE
Update ESLint rules with more ES6 magic

### PR DESCRIPTION
**Pull request by grapegravity**
- `space-in-brackets` became `array-bracket-spacing` and `object-curly-spacing`; settings transferred
- `arrow-parens` requires parens around arrow function parameters
- `arrow-spacing` requires spacing aroung arrow function arrows
- `constructor-super` warns about missing/unnecessary super calls in ES6 constructors
- `no-this-before-super` disallows using `this` before calling `super` in ES6 constructors
- `object-shorthand` prefers shorthand object property declarations
- `prefer-const` warns about variables which are never reassigned and could thus be `const`
- `prefer-spread` advises when spread syntax could replace `Function.prototype.apply`

Also upgrades ESLint and related plugins

### CODE REVIEW

**Comment by deoxxa** [comment]
Disagree with `arrow-parens` purely based on opinion - parentheses around single arguments are lame.

**Comment by grapegravity** [comment]
We had that discussion a few months ago, can’t quite remember the context, but @nelix pushed to include parens, and I now tend to agree that they improve readability somewhat. But again, this is all opinion. :smile:

**Comment by nelix** [comment]
I like parens, because it relate them to "there is a function here".
Little hints like this help me, but I don't really care that much.

**Comment by grapegravity** [comment]
pwned

**Pull request merged**
